FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

# Install Vite globally (optional)
#RUN yarn global add vite

# Copy all source code (if not volume mounted)
COPY . .

EXPOSE 5173

CMD ["yarn", "dev", "--host"]

