apiVersion: v1
stringData:
  minio-root-password: minioadmin
  minio-root-user: minioadmin
  opensearch-admin-password: MPassword123!
kind: Secret
metadata:
  creationTimestamp: "2025-10-07T20:01:33Z"
  name: search-app-secrets
  namespace: search-app-ref
  resourceVersion: "679263"
  uid: 8207ff2e-830c-4757-8294-777e444e02f7
type: Opaque
