imagePullSecrets:
  - name: harbor-cred

backend:
  image:
    repository: harbor.local/search-app/search-backend
    tag: 1.0.1
  replicas: 1

frontend:
  image:
    repository: harbor.local/search-app/search-frontend
    tag: 1.0.1
  replicas: 1
