imagePullSecrets:
  - name: harbor-cred

backendHost: search-app-ref-backend.search-app-ref.svc.cluster.local
backendPort: 8080

backend:
  image:
    repository: harbor.local/search-app/search-backend
    tag: 1.0.1
  replicas: 1

frontend:
  image:
    repository: harbor.local/search-app/search-frontend
    tag: 1.0.1
  replicas: 1
  config:
    oidc:
      enabled: true
      url: http://keycloak.keycloak.svc.cluster.local:8080
      realm: Demo
      clientId: search-app
      baseUrl: https://search-app-ref.local


opensearch:
  image: harbor.local/search-app/opensearch:2.19.4
  replicas: 1

opensearchDashboards:
  image: harbor.local/search-app/opensearch-dashboards:2.19.4
  replicas: 1

ingress:
  enabled: true
  hostname: search-app-ref.local
  tls:
    enabled: true
    secretName: search-app-ref-tls

  env:
    OPENSEARCH_URL: http://search-app-ref-opensearch:9200
    MINIO_ENDPOINT: http://search-app-ref-minio:9000

    #a comment