apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        env:
        - name: OPENSEARCH_URL
          value: http://{{ .Release.Name }}-opensearch:9200
        - name: MINIO_ENDPOINT
          value: http://{{ .Release.Name }}-minio:9000
        {{- if and .Values.minio.credentialsSecretName .Values.minio.credentialsSecretKeys.rootUser }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.credentialsSecretName }}
              key: {{ .Values.minio.credentialsSecretKeys.rootUser }}
        {{- end }}
        {{- if and .Values.minio.credentialsSecretName .Values.minio.credentialsSecretKeys.rootPassword }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.credentialsSecretName }}
              key: {{ .Values.minio.credentialsSecretKeys.rootPassword }}
        {{- end }}
        - name: MINIO_BUCKET
          value: {{ .Values.backend.config.minioBucket }}
        - name: LISTEN_ADDR
          value: {{ .Values.backend.config.listenAddr }}
        ports:
        - containerPort: 8080