```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        env:
        - name: OPENSEARCH_URL
          value: http://{{ .Release.Name }}-opensearch:9200
        - name: MINIO_ENDPOINT
          value: http://{{ .Release.Name }}-minio:9000
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.minio.credentials.rootUser }}
        - name: MINIO_SECRET_KEY
          value: {{ .Values.minio.credentials.rootPassword }}
        - name: MINIO_BUCKET
          value: {{ .Values.backend.config.minioBucket }}
        - name: LISTEN_ADDR
          value: {{ .Values.backend.config.listenAddr }}
        ports:
        - containerPort: 8080
```